<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>bayesianreport</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="BayesianReport_files/libs/clipboard/clipboard.min.js"></script>
<script src="BayesianReport_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="BayesianReport_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="BayesianReport_files/libs/quarto-html/popper.min.js"></script>
<script src="BayesianReport_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="BayesianReport_files/libs/quarto-html/anchor.min.js"></script>
<link href="BayesianReport_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="BayesianReport_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="BayesianReport_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="BayesianReport_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="BayesianReport_files/libs/bootstrap/bootstrap-bb462d781dde1847d9e3ccf7736099dd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<section id="les-modèles-bayésiens-pour-évaluer-les-effets-du-changement-climatique-sur-le-tétras-lyre-tetrao-tetrix" class="level1">
<h1>Les modèles Bayésiens pour évaluer les effets du changement climatique sur le Tétras Lyre (<em>Tetrao tetrix</em>)</h1>
<section id="exporation-des-données" class="level2">
<h2 class="anchored" data-anchor-id="exporation-des-données">1. Exporation des données</h2>
<section id="importation-visualisation-et-formatage" class="level3">
<h3 class="anchored" data-anchor-id="importation-visualisation-et-formatage">1.1 - Importation, visualisation et formatage</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Packages </span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(R2jags)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mgcv)       </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MuMIn)      </span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmmTMB)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Importation des données</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>BirdData <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/tetras.csv"</span>, <span class="at">sep =</span> <span class="st">";"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Permet d'avoir un aperçu global sur le jeu de données et le format des variables</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(BirdData)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 501
Columns: 6
$ region  &lt;chr&gt; "alpes_nord", "alpes_nord", "alpes_sud", "alpes_sud", "alpes_i…
$ site    &lt;int&gt; 8210404, 8210510, 8420802, 8420901, 8420204, 8420205, 8210615,…
$ NAOdjfm &lt;dbl&gt; 2.10, 2.10, 2.10, 2.10, 2.10, 2.10, 2.10, 0.62, 0.62, 0.62, 0.…
$ annee   &lt;int&gt; 1990, 1990, 1990, 1990, 1990, 1990, 1990, 1991, 1991, 1991, 19…
$ poules  &lt;int&gt; 24, 4, 19, 4, 38, 8, 13, 25, 27, 5, 8, 7, 43, 14, 8, 30, 29, 5…
$ jeunes  &lt;int&gt; 34, 9, 38, 10, 31, 13, 7, 47, 35, 9, 14, 7, 28, 28, 17, 24, 22…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Transforme la variable "région" en facteur</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>BirdData<span class="sc">$</span>region <span class="ot">&lt;-</span> <span class="fu">factor</span>(BirdData<span class="sc">$</span>region)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(BirdData<span class="sc">$</span>region)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "alpes_int"     "alpes_nord"    "alpes_sud"     "pre_alpes_occ"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Transforme la variable "site" en facteur</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>BirdData<span class="sc">$</span>site <span class="ot">&lt;-</span> <span class="fu">factor</span>(BirdData<span class="sc">$</span>site)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(BirdData<span class="sc">$</span>site)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "8210103" "8210109" "8210112" "8210201" "8210202" "8210303" "8210304"
 [8] "8210305" "8210404" "8210508" "8210510" "8210604" "8210615" "8210617"
[15] "8210702" "8210703" "8310302" "8410101" "8410102" "8410202" "8410203"
[22] "8410204" "8410301" "8410402" "8410403" "8410404" "8410405" "8410407"
[29] "8410408" "8410502" "8410503" "8410504" "8410506" "8410601" "8410603"
[36] "8410605" "8410701" "8410702" "8410703" "8411101" "8411201" "8411203"
[43] "8411206" "8411207" "8411209" "8420109" "8420201" "8420204" "8420205"
[50] "8420302" "8420601" "8420602" "8420701" "8420801" "8420802" "8420901"
[57] "8421001" "8421002"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Crée une variable région numérique</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>BirdData <span class="ot">&lt;-</span> BirdData <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">region_j =</span> <span class="fu">as.numeric</span>(<span class="fu">factor</span>(region)))</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Crée une variable nombre de jeunes par poule</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>BirdData <span class="ot">&lt;-</span> BirdData <span class="sc">%&gt;%</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ChicksPerHen =</span> <span class="fu">ifelse</span>(jeunes <span class="sc">==</span> <span class="dv">0</span>, <span class="dv">0</span>, jeunes <span class="sc">/</span> poules))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Le jeu de données comprend 501 observations et 6 variables.</p>
<p>Les données sont structurées autour de quatres régions d’étude parmi lesquelles on compte différents sites d’échantillonnage (n=58), avec des mesures répétées de 1990 à 2007.</p>
<p>Les variables region et site ont été identifiées comme des variables catégorielles et ont été converties en facteurs.</p>
<p>Les autres variables correspondent à des variables numériques : l’année d’observation, l’indice climatique NAO (janvier–mars) ainsi que le nombre de poules et le nombre de jeunes, qui sont des variables de comptage.</p>
</section>
<section id="statistiques-résumantes" class="level3">
<h3 class="anchored" data-anchor-id="statistiques-résumantes">1.2 - Statistiques résumantes</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Durée du suivi</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>BirdData <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">annee_min =</span> <span class="fu">min</span>(annee),</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">annee_max =</span> <span class="fu">max</span>(annee),</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">duree_suivi =</span> annee_max <span class="sc">-</span> annee_min <span class="sc">+</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  annee_min annee_max duree_suivi
1      1990      2007          18</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Nombre total de sites</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>BirdData <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n_sites =</span> <span class="fu">n_distinct</span>(site))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  n_sites
1      58</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Nombre de sites par région</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>BirdData <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(region, site) <span class="sc">%&gt;%</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(region, <span class="at">name =</span> <span class="st">"n_sites"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         region n_sites
1     alpes_int      11
2    alpes_nord      33
3     alpes_sud       8
4 pre_alpes_occ       6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Nombre moyen de poules et de jeunes par année </span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>BirdData <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(annee) <span class="sc">%&gt;%</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_poules =</span> <span class="fu">mean</span>(poules),</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_poules   =</span> <span class="fu">sd</span>(poules),</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_jeunes =</span> <span class="fu">mean</span>(jeunes),</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_jeunes   =</span> <span class="fu">sd</span>(jeunes)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(annee)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18 × 5
   annee mean_poules sd_poules mean_jeunes sd_jeunes
   &lt;int&gt;       &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;     &lt;dbl&gt;
 1  1990       15.7      12.4         20.3     13.4 
 2  1991       17.1      13.4         23.1     13.8 
 3  1992       19.1      13.4         14.6      9.81
 4  1993       14.8      11.6         14.7     15.2 
 5  1994       16.3      13.9         28.2     28.9 
 6  1995       21.5      18.8         44.2     50.5 
 7  1996       15.2      12.5         18.9     29.1 
 8  1997       10.2      11.5         13.7     21.5 
 9  1998        9.69      9.44        14.3     12.3 
10  1999        9.44      7.20        15.1     12.7 
11  2000       10.5       9.40        16.4     14.6 
12  2001       11.6       9.96        16.3     15.7 
13  2002       11.5       9.00        20.5     20.1 
14  2003       13.1       9.81        23.0     19.4 
15  2004       13.0      10.3         17.8     15.7 
16  2005       12.6       7.79        20.4     15.0 
17  2006       13.5       8.62        20.2     15.1 
18  2007       13.1       8.82        16.5     11.8 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Statistiques descriptives de l'indice NAO</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>BirdData <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_NAO =</span> <span class="fu">mean</span>(NAOdjfm),</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_NAO   =</span> <span class="fu">sd</span>(NAOdjfm),</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">min_NAO  =</span> <span class="fu">min</span>(NAOdjfm),</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">max_NAO  =</span> <span class="fu">max</span>(NAOdjfm))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   mean_NAO    sd_NAO min_NAO max_NAO
1 0.3607585 0.9022604   -1.46     2.1</code></pre>
</div>
</div>
<p>Les données couvrent une période de 18 ans (1990–2007).</p>
<p>Le nombre de sites par région varie de 6 dans les Pré-Alpes occidentales à 33 dans les Alpes du Nord, avec 8 sites dans les Alpes du Sud et 11 dans les Alpes internes.</p>
<p>Le nombre moyen de poules et de jeunes est variable suivant les années. Il semblerait que le nombre moyen de poules par an était plus important dans les premières années du suivi, mais que à l’inverse, le nombre moyen de jeunes par an etait plus important vers la fin du suivi.</p>
<p>L’indice NAO varie d’une année à l’autre, allant de -1,46 à 2,10, avec une moyenne légèrement positive, reflétant des conditions climatiques variables au cours de la période étudiée.</p>
</section>
<section id="dynamique-temporelle-1990-2007-du-nombre-de-poules-et-de-jeunes-de-tétras-lyre-par-région-alpine" class="level3">
<h3 class="anchored" data-anchor-id="dynamique-temporelle-1990-2007-du-nombre-de-poules-et-de-jeunes-de-tétras-lyre-par-région-alpine">1.3 - Dynamique temporelle (1990-2007) du nombre de poules et de jeunes de Tétras Lyre par région Alpine</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>regional_totals <span class="ot">&lt;-</span> BirdData <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(region, annee) <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">poules =</span> <span class="fu">sum</span>(poules, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">jeunes =</span> <span class="fu">sum</span>(jeunes, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">c</span>(poules, jeunes), <span class="at">names_to =</span> <span class="st">"classe"</span>, <span class="at">values_to =</span> <span class="st">"nombre"</span>)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(regional_totals, <span class="fu">aes</span>(<span class="at">x =</span> annee, <span class="at">y =</span> nombre, <span class="at">color =</span> classe)) <span class="sc">+</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">1.8</span>) <span class="sc">+</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"poules"</span> <span class="ot">=</span> <span class="st">"#1f77b4"</span>, <span class="st">"jeunes"</span> <span class="ot">=</span> <span class="st">"#ff7f0e"</span>)) <span class="sc">+</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Année"</span>, <span class="at">y =</span> <span class="st">"Abondance"</span>, <span class="at">color =</span> <span class="st">"Type"</span>)<span class="sc">+</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()<span class="sc">+</span></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> region, <span class="at">scales =</span> <span class="st">"free_y"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="BayesianReport_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Les graphiques révèlent de fortes disparités régionales dans les effectifs de Tétras Lyre, les Alpes du Nord présentant des abondances nettement supérieures à celles des Pré-Alpes occidentales. Dans l’ensemble des régions, les populations montrent une tendance générale à l’augmentation au cours du temps, bien que le début de cette hausse varie selon la région. Une diminution marquée des effectifs est toutefois observée autour de l’année 2005 dans les Alpes du Nord et les Pré-Alpes occidentales.</p>
<p>La dynamique du nombre de jeunes diffère également selon les régions. Dans les Alpes du Sud, les fluctuations du nombre de jeunes suivent étroitement celles du nombre de poules, tandis que dans les Alpes intérieures, la dynamique des jeunes apparaît plus irrégulière. Les données suggèrent par ailleurs une amélioration progressive du succès reproducteur, avec un nombre de jeunes initialement similaire à celui des poules, puis environ deux fois plus élevé dans les années récentes pour la plupart des régions. Le moment de cette amélioration varie spatialement, apparaissant plus précocement dans les Alpes intérieures (vers 1994), puis dans les Pré-Alpes occidentales (vers 1997) et enfin dans les Alpes du Nord (vers 2000).</p>
</section>
<section id="evolution-du-nombre-de-jeunes-par-poule-de-tétras-lyre-de-1990-à-2007" class="level3">
<h3 class="anchored" data-anchor-id="evolution-du-nombre-de-jeunes-par-poule-de-tétras-lyre-de-1990-à-2007">1.4 - Evolution du nombre de jeunes par poule de Tétras Lyre de 1990 à 2007</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>TotalAnnuel <span class="ot">&lt;-</span> BirdData <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(annee) <span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">ChicksPerHen =</span> <span class="fu">mean</span>(ChicksPerHen, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">c</span>(ChicksPerHen), <span class="at">names_to =</span> <span class="st">"classe"</span>, <span class="at">values_to =</span> <span class="st">"ratioJ/P"</span>)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 2) Graphique lignes</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(TotalAnnuel, <span class="fu">aes</span>(<span class="at">x =</span> annee, <span class="at">y =</span> <span class="st">`</span><span class="at">ratioJ/P</span><span class="st">`</span>, <span class="at">color =</span> classe)) <span class="sc">+</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(    <span class="at">x =</span> <span class="st">"Année"</span>,</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Nombre de jeunes par poules"</span>) <span class="sc">+</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="BayesianReport_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Ce graphique montre que le nombre de jeunes par poule reste globalement stable autour de 1,4 à 1,8, malgré quelques fluctuations marquées au début des années 1990. Après cette période plus variable, la productivité se stabilise progressivement, avec des variations plus modérées d’une année à l’autre, traduisant une reproduction globalement régulière à l’échelle de l’ensemble des régions.</p>
</section>
<section id="evolution-du-nombre-de-jeunes-par-poule-de-tétras-lyre-par-région-de-1990-à-2007" class="level3">
<h3 class="anchored" data-anchor-id="evolution-du-nombre-de-jeunes-par-poule-de-tétras-lyre-par-région-de-1990-à-2007">1.5 - Evolution du nombre de jeunes par poule de Tétras Lyre par région de 1990 à 2007</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>TotalRegional <span class="ot">&lt;-</span> BirdData <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(region, annee) <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a> <span class="at">ChicksPerHen =</span> <span class="fu">mean</span>(ChicksPerHen, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">c</span>(ChicksPerHen), <span class="at">names_to =</span> <span class="st">"classe"</span>, <span class="at">values_to =</span> <span class="st">"ratioJ/P"</span>)</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(TotalRegional, <span class="fu">aes</span>(<span class="at">x =</span> annee, <span class="at">y =</span> <span class="st">`</span><span class="at">ratioJ/P</span><span class="st">`</span>, <span class="at">color =</span> classe)) <span class="sc">+</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">1.8</span>) <span class="sc">+</span></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(    <span class="at">x =</span> <span class="st">"Année"</span>,</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Nombre"</span>  ) <span class="sc">+</span></span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> region, <span class="at">scales =</span> <span class="st">"free_y"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="BayesianReport_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Ce graphique montre que la productivité du Grand Tétras varie nettement selon les régions. les Alpes internes et les Préalpes occidentales présentent globalement des niveaux plus élevés et relativement stables malgré des fluctuations annuelles, tandis que les Alpes du Nord et les Alpes du Sud affichent une variabilité plus marquée, avec des creux prononcés au début des années 1990. Dans l’ensemble, chaque massif suit une dynamique propre, soulignant le poids des conditions locales (climat, enneigement, habitat) dans la réussite reproductrice.</p>
</section>
<section id="evolution-de-lindice-cliamtique-des-oscillations-atlantique-nord-nao-de-1990-à-2007" class="level3">
<h3 class="anchored" data-anchor-id="evolution-de-lindice-cliamtique-des-oscillations-atlantique-nord-nao-de-1990-à-2007">1.6 - Evolution de l’indice cliamtique des Oscillations Atlantique Nord (NAO) de 1990 à 2007</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(BirdData, <span class="fu">aes</span>(<span class="at">x =</span> annee, <span class="at">y =</span> NAOdjfm)) <span class="sc">+</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Année"</span>, <span class="at">y =</span> <span class="st">"Northen Atlantic Oscillations"</span>) <span class="sc">+</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>(<span class="at">base_size =</span> <span class="dv">12</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="BayesianReport_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>NAOTendancyModel <span class="ot">&lt;-</span> <span class="fu">lm</span>(NAOdjfm <span class="sc">~</span> annee, <span class="at">data =</span> BirdData)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(NAOTendancyModel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = NAOdjfm ~ annee, data = BirdData)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.1903 -0.5621  0.1288  0.3942  1.2796 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 138.615541  18.013449   7.695 7.62e-14 ***
annee        -0.069081   0.009001  -7.675 8.76e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.8542 on 499 degrees of freedom
Multiple R-squared:  0.1056,    Adjusted R-squared:  0.1038 
F-statistic: 58.91 on 1 and 499 DF,  p-value: 8.764e-14</code></pre>
</div>
</div>
<p>L’indice NAO hivernal (décembre–mars) présente une forte variabilité interannuelle sur la période 1990–2007, alternant fréquemment entre phases positives et négatives. Cette alternance traduit une succession d’hivers contrastés en termes de conditions climatiques à l’échelle de l’Atlantique Nord. Il semblerait globalement que malgrè une grande variabilité, le NAO suive une tendance négative. Le modèle linéaire met en évidence cette tendance temporelle négative de l’indice NAO hivernal au cours de la période étudiée (β = −0.069 ± 0.009, t = −7.68, p &lt; 0.001).</p>
<p>Cette tendance négative de la NAO hivernale suggère une évolution vers des hivers plus froids et potentiellement plus neigeux dans les Alpes au cours de la période étudiée. De telles variations des conditions hivernales peuvent influencer directement la survie hivernale des adultes ainsi que, de manière indirecte, le succès reproducteur ultérieur des populations de Tétras Lyre, notamment via leurs effets sur l’état corporel des femelles et la phénologie de reproduction.</p>
</section>
<section id="hypothèses-et-ojectifs-de-lanalyse-statistique" class="level3">
<h3 class="anchored" data-anchor-id="hypothèses-et-ojectifs-de-lanalyse-statistique">1.7 - Hypothèses et ojectifs de l’Analyse statistique</h3>
<p>Dans cette étude, notre objectif est d’évaluer dans quelle mesure les populations alpines de Tétras lyre, une espèce boréo-alpine localisée en limite sud de son aire de répartition, sont affectées par les variations climatiques récentes et le réchauffement global. Nous avons formulé l’hypothèse que le succès reproducteur, trait démographique particulièrement sensible aux fluctuations climatiques chez de nombreuses espèces d’oiseaux, serait influencé à la fois par les conditions hivernales, déterminantes pour l’état physiologique et les réserves énergétiques des femelles avant la ponte, et par les conditions de début de printemps, qui conditionnent la qualité des ressources alimentaires disponibles avant l’élevage des jeunes.</p>
<p>Plus précisément, nous nous attendions à ce que la variabilité interannuelle de la NAO (North Atlantic Oscillation), utilisée comme indicateur synthétique du climat, affecte la productivité des populations, et que d’éventuelles tendances à long terme de la NAO liées au changement climatique se traduisent par une modification du succès reproducteur à l’échelle des Alpes. Pour tester ces hypothèses, nous avons analysé des séries de recensements annuels de Tétras lyre entre 1990 et 2007, en recherchant à la fois des tendances temporelles globales et des relations entre indices reproducteurs et NAO seulement d’hiver</p>
</section>
</section>
<section id="ajustement-des-modèles-simplifiés-fréquentistes" class="level2">
<h2 class="anchored" data-anchor-id="ajustement-des-modèles-simplifiés-fréquentistes">2. Ajustement des modèles simplifiés (fréquentistes)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Préparation des données pour les modèles fréquentists</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="co"># On fait un offset car on modélise le nombre de jeunes en fonction du nombre de poules donc on enlève les lignes avec poules = 0</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>BirdData <span class="sc">%&gt;%</span>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(poules), <span class="sc">!</span><span class="fu">is.na</span>(jeunes), poules <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Construction des modèles fréquentists (semblables à l'article de Barnagaud et al., 2011)</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Modèle nul (seulement site)</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>GLMMModel1  <span class="ot">&lt;-</span> <span class="fu">glmmTMB</span>(jeunes <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>site), </span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>               <span class="at">offset =</span> <span class="fu">log</span>(poules), <span class="at">family =</span> <span class="fu">poisson</span>(), <span class="at">data =</span> BirdData)</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Régions seules</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>GLMMModel2  <span class="ot">&lt;-</span> <span class="fu">glmmTMB</span>(jeunes <span class="sc">~</span> region <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>site), </span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>               <span class="at">offset =</span> <span class="fu">log</span>(poules), <span class="at">family =</span> <span class="fu">poisson</span>(), <span class="at">data =</span> BirdData)</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a><span class="co"># NAO linéaire seul</span></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>GLMMModel3 <span class="ot">&lt;-</span> <span class="fu">glmmTMB</span>(jeunes <span class="sc">~</span> <span class="fu">scale</span>(NAOdjfm, <span class="at">center =</span> <span class="cn">TRUE</span>, <span class="at">scale =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>site), </span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>               <span class="at">offset =</span> <span class="fu">log</span>(poules), <span class="at">family =</span> <span class="fu">poisson</span>(), <span class="at">data =</span> BirdData)</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a><span class="co"># NAO linéaire + effet quadratique</span></span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>GLMMModel4 <span class="ot">&lt;-</span> <span class="fu">glmmTMB</span>(jeunes <span class="sc">~</span> <span class="fu">scale</span>(NAOdjfm, <span class="at">center =</span> <span class="cn">TRUE</span>, <span class="at">scale =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> <span class="fu">I</span>(<span class="fu">scale</span>(NAOdjfm, <span class="at">center =</span> <span class="cn">TRUE</span>, <span class="at">scale =</span> <span class="cn">FALSE</span>)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>site), </span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>               <span class="at">offset =</span> <span class="fu">log</span>(poules), <span class="at">family =</span> <span class="fu">poisson</span>(), <span class="at">data =</span> BirdData)</span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Régions + NAO linéaire</span></span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a>GLMMModel5 <span class="ot">&lt;-</span> <span class="fu">glmmTMB</span>(jeunes <span class="sc">~</span> region <span class="sc">+</span> <span class="fu">scale</span>(NAOdjfm, <span class="at">center =</span> <span class="cn">TRUE</span>, <span class="at">scale =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>site), </span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a>                <span class="at">offset =</span> <span class="fu">log</span>(poules), <span class="at">family =</span> <span class="fu">poisson</span>(), <span class="at">data =</span> BirdData)</span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Régions + NAO linéaire et effet quadratique </span></span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a>GLMMModel6 <span class="ot">&lt;-</span> <span class="fu">glmmTMB</span>(jeunes <span class="sc">~</span> region <span class="sc">+</span> <span class="fu">scale</span>(NAOdjfm, <span class="at">center =</span> <span class="cn">TRUE</span>, <span class="at">scale =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> <span class="fu">I</span>(<span class="fu">scale</span>(NAOdjfm, <span class="at">center =</span> <span class="cn">TRUE</span>, <span class="at">scale =</span> <span class="cn">FALSE</span>)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>site), </span>
<span id="cb25-28"><a href="#cb25-28" aria-hidden="true" tabindex="-1"></a>                <span class="at">offset =</span> <span class="fu">log</span>(poules), <span class="at">family =</span> <span class="fu">poisson</span>(), <span class="at">data =</span> BirdData)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Comparaison des modèles fréquentistes par AIC</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>Models <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">m0=</span>GLMMModel1, <span class="at">mR=</span>GLMMModel2, <span class="at">mN1=</span>GLMMModel3, <span class="at">mN2=</span>GLMMModel4, <span class="at">mRN1=</span>GLMMModel5, <span class="at">mRN2=</span>GLMMModel6)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>AICComparison <span class="ot">&lt;-</span> MuMIn<span class="sc">::</span><span class="fu">model.sel</span>(Models, <span class="at">rank =</span> <span class="st">"AIC"</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>BestModel <span class="ot">&lt;-</span> <span class="fu">rownames</span>(AICComparison)[<span class="dv">1</span>]</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>BestModel <span class="ot">&lt;-</span> Models[[ BestModel ]]</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(BestModel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Family: poisson  ( log )
Formula:          
jeunes ~ region + scale(NAOdjfm, center = TRUE, scale = FALSE) +  
    I(scale(NAOdjfm, center = TRUE, scale = FALSE)^2) + (1 |      site)
Data: BirdData
 Offset: log(poules)

      AIC       BIC    logLik -2*log(L)  df.resid 
   4028.3    4057.9   -2007.2    4014.3       494 

Random effects:

Conditional model:
 Groups Name        Variance Std.Dev.
 site   (Intercept) 0.07796  0.2792  
Number of obs: 501, groups:  site, 58

Conditional model:
                                                  Estimate Std. Error z value
(Intercept)                                        0.56455    0.09291   6.076
regionalpes_nord                                  -0.19488    0.10635  -1.832
regionalpes_sud                                   -0.26773    0.14695  -1.822
regionpre_alpes_occ                                0.09101    0.15345   0.593
scale(NAOdjfm, center = TRUE, scale = FALSE)       0.01519    0.01214   1.251
I(scale(NAOdjfm, center = TRUE, scale = FALSE)^2) -0.06535    0.01173  -5.570
                                                  Pr(&gt;|z|)    
(Intercept)                                       1.23e-09 ***
regionalpes_nord                                    0.0669 .  
regionalpes_sud                                     0.0685 .  
regionpre_alpes_occ                                 0.5531    
scale(NAOdjfm, center = TRUE, scale = FALSE)        0.2110    
I(scale(NAOdjfm, center = TRUE, scale = FALSE)^2) 2.55e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>L’analyse par sélection AIC (modèles comparés: m0, mR, mN1, mN2, mRN1, mRN2) montre que le modèle mRN2 (régions + NAO + NAO² + (1|site)) est le meilleur (AIC=4028.3), devant le modèle climat seul quadratique mN2 (AIC=4029.8), ce qui indique que la NAO (linéaire + quadratique) explique l’essentiel de la variation, et que les régions ajoutent un gain modeste mais réel.</p>
<p>Ce meilleur modèle inclut à la fois les effets de région, de l’indice NAO hivernal et de son terme quadratique, ainsi qu’un effet aléatoire pour le site (σ_site ≈ 0.28). Les résultats indiquent que le succès reproducteur des Tétras Lyre augmente de manière significative avec l’augmentation de l’indice NAO (effet linéaire : β = 0.062 ± 0.014, p &lt; 0.001), mais que cette relation est non linéaire : le terme quadratique négatif (β = −0.065 ± 0.012, p &lt; 0.001) suggère que les valeurs extrêmes de NAO, très positives ou très négatives, sont associées à un recrutement plus faible, tandis qu’un NAO proche de la moyenne favorise un nombre plus élevé de jeunes.</p>
<p>Concernant les régions, les Alpes du Sud et les Alpes du Nord présentent une tendance à un recrutement légèrement inférieur par rapport à la référence (Alpes intérieures), bien que ces effets soient marginalement significatifs (p ≈ 0.067 et 0.069). Les Pré-Alpes occidentales ne diffèrent pas de la référence. Enfin, l’effet aléatoire du site montre une variabilité modérée entre sites (σ ≈ 0.28), indiquant que des facteurs locaux peuvent également influencer le succès reproducteur</p>
<p>Autrement dit, ce premier modèle simple, hiérarchique et adapté à des données de comptage hétérogènes répond directement à la question écologique centrale: comment la NAO hivernale et les différences régionales influencent-elles le taux de reproduction (jeunes par poule) du Grand Tétras?</p>
</section>
<section id="ajustement-du-modèle-bayésien" class="level2">
<h2 class="anchored" data-anchor-id="ajustement-du-modèle-bayésien">3. Ajustement du modèle Bayésien</h2>
<section id="ecriture-du-modèle-initialisation-des-paramètres-et-definition-des-priors" class="level3">
<h3 class="anchored" data-anchor-id="ecriture-du-modèle-initialisation-des-paramètres-et-definition-des-priors">3.1 - Ecriture du modèle, initialisation des paramètres et definition des priors</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Construction du modèle Bayésien </span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="do">## Modèle Nombre de jeunes \~ par poules Région + NAO linéaire + quadratique + (1\| Site) avec un OFFSET sur le nombre de poules</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>ModBayPoisson_region_NAO_quad_site <span class="ot">&lt;-</span> <span class="cf">function</span>() {</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n){</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>    jeunes[i] <span class="sc">~</span> <span class="fu">dpois</span>(lambda[i])</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">log</span>(lambda[i]) <span class="ot">&lt;-</span> </span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>      a[site[i]] <span class="sc">+</span>                 <span class="co"># effet aléatoire site</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>      b_region[region[i]] <span class="sc">+</span>        <span class="co"># effet fixe région</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>      beta_NAO_lin  <span class="sc">*</span> x[i] <span class="sc">+</span>        <span class="co"># NAO linéaire</span></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>      beta_NAO_quad <span class="sc">*</span> <span class="fu">pow</span>(x[i], <span class="dv">2</span>) <span class="co"># NAO quadratique</span></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>      <span class="sc">+</span> <span class="fu">log</span>(poules[i])}             <span class="co"># OFFSET</span></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Effet aléatoire site</span></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span>(s <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>nbsite){</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>    a[s] <span class="sc">~</span> <span class="fu">dnorm</span>(mu_site, tau_site)}</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>  mu_site <span class="sc">~</span> <span class="fu">dnorm</span>(<span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>  tau_site <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">/</span> <span class="fu">pow</span>(sd_site, <span class="dv">2</span>)</span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a>  sd_site <span class="sc">~</span> <span class="fu">dunif</span>(<span class="fl">0.001</span>, <span class="dv">2</span>)</span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Effet fixe région</span></span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span>(r <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>Nregion){</span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a>    b_region[r] <span class="sc">~</span> <span class="fu">dnorm</span>(<span class="dv">0</span>, <span class="dv">1</span>)}</span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Effets NAO</span></span>
<span id="cb28-24"><a href="#cb28-24" aria-hidden="true" tabindex="-1"></a>  beta_NAO_lin  <span class="sc">~</span> <span class="fu">dnorm</span>(<span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb28-25"><a href="#cb28-25" aria-hidden="true" tabindex="-1"></a>  beta_NAO_quad <span class="sc">~</span> <span class="fu">dnorm</span>(<span class="dv">0</span>, <span class="dv">1</span>)}</span>
<span id="cb28-26"><a href="#cb28-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-27"><a href="#cb28-27" aria-hidden="true" tabindex="-1"></a><span class="do">## Préparation des données</span></span>
<span id="cb28-28"><a href="#cb28-28" aria-hidden="true" tabindex="-1"></a>dataOffset <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb28-29"><a href="#cb28-29" aria-hidden="true" tabindex="-1"></a>  <span class="at">n       =</span> <span class="fu">nrow</span>(BirdData),</span>
<span id="cb28-30"><a href="#cb28-30" aria-hidden="true" tabindex="-1"></a>  <span class="at">jeunes  =</span> BirdData<span class="sc">$</span>jeunes,</span>
<span id="cb28-31"><a href="#cb28-31" aria-hidden="true" tabindex="-1"></a>  <span class="at">poules  =</span> BirdData<span class="sc">$</span>poules,</span>
<span id="cb28-32"><a href="#cb28-32" aria-hidden="true" tabindex="-1"></a>  <span class="at">x       =</span> <span class="fu">as.numeric</span>(<span class="fu">scale</span>(BirdData<span class="sc">$</span>NAOdjfm)),</span>
<span id="cb28-33"><a href="#cb28-33" aria-hidden="true" tabindex="-1"></a>  <span class="at">site    =</span> <span class="fu">as.numeric</span>(<span class="fu">factor</span>(BirdData<span class="sc">$</span>site)),</span>
<span id="cb28-34"><a href="#cb28-34" aria-hidden="true" tabindex="-1"></a>  <span class="at">nbsite  =</span> <span class="fu">length</span>(<span class="fu">unique</span>(BirdData<span class="sc">$</span>site)),</span>
<span id="cb28-35"><a href="#cb28-35" aria-hidden="true" tabindex="-1"></a>  <span class="at">region  =</span> <span class="fu">as.numeric</span>(<span class="fu">factor</span>(BirdData<span class="sc">$</span>region)),</span>
<span id="cb28-36"><a href="#cb28-36" aria-hidden="true" tabindex="-1"></a>  <span class="at">Nregion =</span> <span class="fu">length</span>(<span class="fu">unique</span>(BirdData<span class="sc">$</span>region)))</span>
<span id="cb28-37"><a href="#cb28-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-38"><a href="#cb28-38" aria-hidden="true" tabindex="-1"></a><span class="do">## Initialisations et paramètres à surveiller</span></span>
<span id="cb28-39"><a href="#cb28-39" aria-hidden="true" tabindex="-1"></a>init1 <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb28-40"><a href="#cb28-40" aria-hidden="true" tabindex="-1"></a>  <span class="at">mu_site =</span> <span class="dv">0</span>,</span>
<span id="cb28-41"><a href="#cb28-41" aria-hidden="true" tabindex="-1"></a>  <span class="at">a =</span> <span class="fu">rep</span>(<span class="dv">0</span>, dataOffset<span class="sc">$</span>nbsite),</span>
<span id="cb28-42"><a href="#cb28-42" aria-hidden="true" tabindex="-1"></a>  <span class="at">b_region =</span> <span class="fu">rep</span>(<span class="dv">0</span>, dataOffset<span class="sc">$</span>Nregion),</span>
<span id="cb28-43"><a href="#cb28-43" aria-hidden="true" tabindex="-1"></a>  <span class="at">beta_NAO_lin =</span> <span class="dv">0</span>,</span>
<span id="cb28-44"><a href="#cb28-44" aria-hidden="true" tabindex="-1"></a>  <span class="at">beta_NAO_quad =</span> <span class="dv">0</span>,</span>
<span id="cb28-45"><a href="#cb28-45" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd_site =</span> <span class="dv">1</span>)</span>
<span id="cb28-46"><a href="#cb28-46" aria-hidden="true" tabindex="-1"></a>init2 <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb28-47"><a href="#cb28-47" aria-hidden="true" tabindex="-1"></a>  <span class="at">mu_site =</span> <span class="fl">0.5</span>,</span>
<span id="cb28-48"><a href="#cb28-48" aria-hidden="true" tabindex="-1"></a>  <span class="at">a =</span> <span class="fu">rep</span>(<span class="fl">0.5</span>, dataOffset<span class="sc">$</span>nbsite),</span>
<span id="cb28-49"><a href="#cb28-49" aria-hidden="true" tabindex="-1"></a>  <span class="at">b_region =</span> <span class="fu">rep</span>(<span class="fl">0.5</span>, dataOffset<span class="sc">$</span>Nregion),</span>
<span id="cb28-50"><a href="#cb28-50" aria-hidden="true" tabindex="-1"></a>  <span class="at">beta_NAO_lin =</span> <span class="fl">0.5</span>,</span>
<span id="cb28-51"><a href="#cb28-51" aria-hidden="true" tabindex="-1"></a>  <span class="at">beta_NAO_quad =</span> <span class="sc">-</span><span class="fl">0.5</span>,</span>
<span id="cb28-52"><a href="#cb28-52" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd_site =</span> <span class="dv">2</span>)</span>
<span id="cb28-53"><a href="#cb28-53" aria-hidden="true" tabindex="-1"></a>initsOffset <span class="ot">&lt;-</span> <span class="fu">list</span>(init1, init2)</span>
<span id="cb28-54"><a href="#cb28-54" aria-hidden="true" tabindex="-1"></a>paramsOffset <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="st">"mu_site"</span>, <span class="st">"a"</span>, <span class="st">"b_region"</span>, <span class="st">"beta_NAO_lin"</span>, <span class="st">"beta_NAO_quad"</span>, <span class="st">"sd_site"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Pour analyser l’effet de l’indice NAO hivernal sur le succès reproducteur des Tétras Lyre tout en tenant compte des variations régionales et locales, nous reconstruit le meilleur modèle (issu des analyses fréquentistes de Barnagaud et al., 2011) en bayésien avec une distribution de Poisson. La variable réponse est le nombre de jeunes par site et par année, avec un offset logarithmique sur le nombre de poules, afin de modéliser le recrutement relatif.</p>
<p>Le modèle inclut :</p>
<ul>
<li><p>un effet fixe pour la région, pour capturer les différences spatiales entre les Alpes du Nord, du Sud et les Pré-Alpes occidentales,</p></li>
<li><p>un effet linéaire et quadratique de l’indice NAO, afin de tester une relation non linéaire entre conditions climatiques hivernales et succès reproducteur,</p></li>
<li><p>un effet aléatoire pour le site, pour tenir compte de la variabilité locale non expliquée par les facteurs fixes.</p></li>
</ul>
<p>La construction du modèl bayésien a été réalisée dans JAGS. Deux chaînes MCMC ont été initialisées à partir de valeurs différentes afin de vérifier la convergence, et les paramètres surveillés comprenaient les effets fixes (région, NAO linéaire et quadratique) ainsi que les effets aléatoires du site et leur variance.</p>
<p>Afin d’assurer la stabilité du modèle tout en autorisant une variabilité biologiquement réaliste, nous avons utilisé des priors gaussiens modérément informatifs. Les effets aléatoires de site sont centrés sur zéro et régularisés par une variance bornée, traduisant une variabilité intersite modérée du succès reproducteur. Les effets fixes de région sont également centrés sur zéro avec une variance unitaire, ce qui permet de représenter des différences régionales plausibles sans autoriser des écarts extrêmes. Enfin, les coefficients linéaire et quadratique de l’indice d’oscillation nord-atlantique (NAO) sont assignés à des priors centrés sur zéro et de variance unitaire, reflétant l’hypothèse que l’influence du climat hivernal sur le recrutement est modérée et symétrique autour de l’absence d’effet</p>
</section>
<section id="exécution-du-modèle-bayésien" class="level3">
<h3 class="anchored" data-anchor-id="exécution-du-modèle-bayésien">3.2 - Exécution du modèle Bayésien</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Lancement du modèle Baysésien</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>JAGSModel <span class="ot">&lt;-</span> <span class="fu">jags</span>(</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dataOffset,</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">inits =</span> initsOffset,</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">parameters.to.save =</span> paramsOffset,</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.file =</span> ModBayPoisson_region_NAO_quad_site,</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">n.chains =</span> <span class="dv">2</span>,</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">n.iter =</span> <span class="dv">10000</span>,</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">n.burnin =</span> <span class="dv">5000</span>,</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">n.thin =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Ici , nous avons exécuté le modèle bayésien en utilisant le package R2jags, avec les données préparées précédemment. Le modèle a été lancé avec deux chaînes MCMC, chacune comportant 10 000 itérations, dont les 5000 premières ont été utilisées comme période de burn-in pour permettre la convergence des chaînes. Les paramètres d’intérêt, incluant les effets fixes et aléatoires, ont été surveillés tout au long de l’exécution du modèle.On a choisi n.thin = 2 pour ne conserver qu’une itération sur deux des chaînes MCMC, ce qui permet de réduire la autocorrélation entre échantillons consécutifs.</p>
</section>
<section id="diagnostic-de-convergence" class="level3">
<h3 class="anchored" data-anchor-id="diagnostic-de-convergence">3.3 - Diagnostic de convergence</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Vérification de la convergence des paramètres (Rhat)</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(JAGSModel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Traceplots de la convergence des paramètres</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>mcmc_mat <span class="ot">&lt;-</span> JAGSModel<span class="sc">$</span>BUGSoutput<span class="sc">$</span>sims.matrix</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>mcmc_obj <span class="ot">&lt;-</span> <span class="fu">as.mcmc</span>(mcmc_mat)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="fu">traceplot</span>(</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  mcmc_obj[, <span class="fu">c</span>(<span class="st">"mu_site"</span>,</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>               <span class="st">"sd_site"</span>,</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>               <span class="st">"beta_NAO_lin"</span>,</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>               <span class="st">"beta_NAO_quad"</span>,</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>               <span class="st">"b_region[1]"</span>,</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>               <span class="st">"b_region[2]"</span>,</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>               <span class="st">"b_region[3]"</span>,</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>               <span class="st">"b_region[4]"</span>)],</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">ask =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="BayesianReport_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="BayesianReport_files/figure-html/unnamed-chunk-13-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="BayesianReport_files/figure-html/unnamed-chunk-13-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="BayesianReport_files/figure-html/unnamed-chunk-13-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="BayesianReport_files/figure-html/unnamed-chunk-13-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="BayesianReport_files/figure-html/unnamed-chunk-13-6.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="BayesianReport_files/figure-html/unnamed-chunk-13-7.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="BayesianReport_files/figure-html/unnamed-chunk-13-8.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Les diagnostics de convergence, basés sur les valeurs de Rhat et les traceplots, indiquent que toutes les chaînes MCMC ont convergé de manière satisfaisante pour les différents paramètres. Les valeurs de Rhat sont proches de 1, suggérant une bonne convergence, et les traceplots montrent une exploration adéquate de l’espace des paramètres sans tendance apparente.</p>
</section>
</section>
<section id="résultats" class="level2">
<h2 class="anchored" data-anchor-id="résultats">4. Résultats</h2>
<section id="comparaison-des-modèles-fréquentistes-et-baysésiens" class="level3">
<h3 class="anchored" data-anchor-id="comparaison-des-modèles-fréquentistes-et-baysésiens">4.1 - Comparaison des modèles fréquentistes et baysésiens</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(JAGSModel)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(GLMMModel6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Les résultats du modèle bayésien (JAGS) et du modèle fréquentiste (GLMM) montrent de fortes similarités dans les estimations des paramètres. Dans les deux modèles, la seule variable ressortant significatives est le coefficient quadratique de la NAO (beta_NAO_quad). Pour cette variable, le GLMM estime -0,065 (SE = 0,012), tandis que le modèle JAGS donne -0,050 (IC 95 % : -0.069 – -0.032). Les deux approches montrent donc un effet négatif significatif et de même ordre de grandeur, confirmant la robustesse de l’influence quadratique de la NAO sur le nombre de jeunes de Tétras Lyre observés.</p>
<p>De plus, les deux modèles estiment un effet aléatoire site de même ordre de grandeur (GLMM : SD ≈ 0,28 ; JAGS : SD ≈ 0,3, IC 95% : 0,24–0,39), indiquant que la variabilité inter-sites est cohérente et bien capturée par les deux approches.</p>
</section>
<section id="effet-de-lindice-nao-sur-le-nombre-de-jeunes-par-poule-selon-les-régions" class="level3">
<h3 class="anchored" data-anchor-id="effet-de-lindice-nao-sur-le-nombre-de-jeunes-par-poule-selon-les-régions">4.2 - Effet de l’indice NAO sur le nombre de jeunes par poule selon les régions</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Récupère les simulations postérieures du modèle JAGS</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>JAGSSimulations <span class="ot">&lt;-</span> JAGSModel<span class="sc">$</span>BUGSoutput<span class="sc">$</span>sims.list</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Crée une séquence de valeurs NAO pour les prédictions et une grille combinant NAO et régions</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>NAO_seq <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(dataOffset<span class="sc">$</span>x), <span class="fu">max</span>(dataOffset<span class="sc">$</span>x), <span class="at">length.out =</span> <span class="dv">100</span>)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>pred_grid <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">x =</span> NAO_seq, <span class="at">region =</span> <span class="dv">1</span><span class="sc">:</span>dataOffset<span class="sc">$</span>Nregion)</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a><span class="do">## Nombre d'itérations MCMC</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>n_iter <span class="ot">&lt;-</span> <span class="fu">length</span>(JAGSSimulations<span class="sc">$</span>beta_NAO_lin)</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a><span class="do">## Matrice vide pour stocker les prédictions pour chaque combinaison NAO/région et itération</span></span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>pred_mat <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, <span class="at">nrow =</span> <span class="fu">nrow</span>(pred_grid), <span class="at">ncol =</span> n_iter)</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a><span class="do">## Boucle pour calculer les prédictions sur toutes les itérations MCMC</span></span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n_iter){</span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span>(r <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>dataOffset<span class="sc">$</span>Nregion){</span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a>    idx <span class="ot">&lt;-</span> <span class="fu">which</span>(pred_grid<span class="sc">$</span>region <span class="sc">==</span> r)          <span class="co"># lignes correspondant à cette région</span></span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a>    eta <span class="ot">&lt;-</span> JAGSSimulations<span class="sc">$</span>mu_site[i] <span class="sc">+</span></span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>           JAGSSimulations<span class="sc">$</span>b_region[i, r] <span class="sc">+</span></span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a>           JAGSSimulations<span class="sc">$</span>beta_NAO_lin[i]  <span class="sc">*</span> pred_grid<span class="sc">$</span>x[idx] <span class="sc">+</span></span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a>           JAGSSimulations<span class="sc">$</span>beta_NAO_quad[i] <span class="sc">*</span> pred_grid<span class="sc">$</span>x[idx]<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb33-23"><a href="#cb33-23" aria-hidden="true" tabindex="-1"></a>    pred_mat[idx, i] <span class="ot">&lt;-</span> <span class="fu">exp</span>(eta)}}</span>
<span id="cb33-24"><a href="#cb33-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-25"><a href="#cb33-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-26"><a href="#cb33-26" aria-hidden="true" tabindex="-1"></a><span class="do">## Calcule la moyenne des prédictions sur toutes les itérations et convertit les indices de région en facteurs lisibles</span></span>
<span id="cb33-27"><a href="#cb33-27" aria-hidden="true" tabindex="-1"></a>pred_df <span class="ot">&lt;-</span> pred_grid <span class="sc">%&gt;%</span></span>
<span id="cb33-28"><a href="#cb33-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb33-29"><a href="#cb33-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean =</span> <span class="fu">apply</span>(pred_mat, <span class="dv">1</span>, mean),</span>
<span id="cb33-30"><a href="#cb33-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">region =</span> <span class="fu">factor</span>(region,</span>
<span id="cb33-31"><a href="#cb33-31" aria-hidden="true" tabindex="-1"></a>                    <span class="at">levels =</span> <span class="dv">1</span><span class="sc">:</span>dataOffset<span class="sc">$</span>Nregion,       </span>
<span id="cb33-32"><a href="#cb33-32" aria-hidden="true" tabindex="-1"></a>                    <span class="at">labels =</span> <span class="fu">levels</span>(BirdData<span class="sc">$</span>region))   </span>
<span id="cb33-33"><a href="#cb33-33" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb33-34"><a href="#cb33-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-35"><a href="#cb33-35" aria-hidden="true" tabindex="-1"></a><span class="do">## Graphique de l'effet de la NAO sur le nombre de jeunes par poule selon les régions</span></span>
<span id="cb33-36"><a href="#cb33-36" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb33-37"><a href="#cb33-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(</span>
<span id="cb33-38"><a href="#cb33-38" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> pred_df,</span>
<span id="cb33-39"><a href="#cb33-39" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> mean, <span class="at">colour =</span> region),</span>
<span id="cb33-40"><a href="#cb33-40" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb33-41"><a href="#cb33-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(</span>
<span id="cb33-42"><a href="#cb33-42" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> BirdData,</span>
<span id="cb33-43"><a href="#cb33-43" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> NAOdjfm, <span class="at">y =</span> ChicksPerHen),</span>
<span id="cb33-44"><a href="#cb33-44" aria-hidden="true" tabindex="-1"></a>    <span class="at">colour =</span> <span class="st">"grey70"</span>,</span>
<span id="cb33-45"><a href="#cb33-45" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.6</span>,</span>
<span id="cb33-46"><a href="#cb33-46" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="fl">1.8</span>) <span class="sc">+</span></span>
<span id="cb33-47"><a href="#cb33-47" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Northen Atlantic Oscillations"</span>, <span class="at">y =</span> <span class="st">"Number of Chicks per Hen"</span>, <span class="at">colour =</span> <span class="st">"Region"</span>) <span class="sc">+</span></span>
<span id="cb33-48"><a href="#cb33-48" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>(<span class="at">base_size =</span> <span class="dv">14</span>) <span class="sc">+</span></span>
<span id="cb33-49"><a href="#cb33-49" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="fl">0.3</span>, <span class="fl">2.8</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="BayesianReport_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Le graphique illustre l’effet de l’oscillation nord-atlantique (NAO) sur le nombre de poussins par poule, en tenant compte des différences entre régions. On observe une relation quadratique entre la NAO et le nombre de poussins : le nombre de jeunes tend à augmenter pour des valeurs modérées de NAO, puis diminue pour des valeurs extrêmes, indiquant un optimum intermédiaire. Parmi les régions, la région pré-alpes-occidentales (violet) présente systématiquement le nombre de poussins le plus élevé, suivie de la région alpes_int (rouge), tandis que les régions alpes_nord (vert) et alpes_sud (bleu) affichent des niveaux plus faibles et relativement similaires.</p>
<p>Cela signifie que les hivers très froids et humides réduisent la reproduction, probablement parce que les femelles doivent mobiliser leur énergie pour survivre plutôt que pour se reproduire. De même, les hivers plus chauds et secs que la normale limitent également le succès reproducteur, probablement en réduisant la protection contre le froid ou la prédation et en diminuant la disponibilité et la qualité des ressources végétales. Les variations régionales montrent que certaines zones, comme les pré-alpes-occidentales, présentent systématiquement un nombre de poussins plus élevé, tandis que d’autres régions affichent des niveaux plus faibles et similaires</p>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">5. Discussion</h2>
<p>Nos analyses bayésiennes mettent en évidence une relation non linéaire entre la NAO hivernale et le succès reproducteur du Tétras lyre, caractérisée par un effet linéaire positif et un effet quadratique négatif. Cette forme concave, qui indique une productivité maximale pour des valeurs intermédiaires de la NAO, est parfaitement cohérente avec les résultats de Barnagaud et al.&nbsp;(2011), qui décrivent également un optimum autour de valeurs positives modérées du NAO d’hiver. Dans notre modèle, l’optimum estimé se situe autour de NAO ≈ 0,5, très proche de l’optimum rapporté dans l’étude originale (≈ 0,4). Cette convergence indique que, malgré les approches statistiques différentes, la dynamique biologique décrite demeure robuste&nbsp;: les hivers modérément doux et secs favorisent davantage la reproduction que les hivers très négatifs ou très positifs, qui s’accompagnent d’une baisse de productivité. Les effets régionaux, également présents dans notre meilleur modèle, corroborent ceux observés par Barnagaud et al.&nbsp;(2011), soulignant l’importance des contrastes bioclimatiques alpins dans la variabilité spatiale du succès reproducteur.</p>
<p>Cependant, contrairement à l’étude de référence, les intervalles de crédibilité de nos coefficients incluent légèrement zéro, suggérant une incertitude un peu plus élevée autour des estimations. Ceci peut s’expliquer par plusieurs facteurs : (i) l’utilisation d’un modèle bayésien normal sur une variable dérivée (chicks per hen), alors que Barnagaud et al.&nbsp;utilisaient des GLMM Poisson avec offset, plus adaptés à des données de comptage ; (ii) une possible colinéarité accrue entre les termes linéaire et quadratique lorsque la NAO n’est pas centrée ; et (iii) des différences éventuelles d’étendue spatiale ou temporelle entre nos données et celles couvertes dans leur étude. Malgré cela, les motifs fonctionnels identifiés – absence de tendance temporelle marquée, importance des effets spatiaux, parabole concave de la NAO d’hiver – restent remarquablement similaires. Ces résultats confirment la conclusion de l’étude selon laquelle les populations alpines de Tétras lyre semblent capables de suivre les tendances climatiques récentes, tout en étant potentiellement vulnérables à une augmentation de la fréquence des années extrêmes.</p>
<p>Dans l’ensemble, nos analyses confortent les interprétations de Barnagaud et al.&nbsp;: le Tétras lyre optimise sa reproduction sous des conditions hivernales correspondant à des valeurs moyennes à modérément positives du NAO, ce qui reflète une capacité d’ajustement aux conditions climatiques des dernières décennies. Cette cohérence entre deux approches méthodologiques distinctes renforce la confiance dans le rôle déterminant de la NAO hivernale comme indicateur synthétique des influences climatiques sur le succès reproducteur de cette espèce alpine.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>